### ISSUE TITLE
Recurring holidays

### ISSUE THREAD

**Issue by soulfire03** [chas-iot/calendar#10]
Hello,
Would it be possible to set a date like "20YY-12-25" for recurring holidays, so we would not be required to change all dates every next year.

Thanks!

**Comment by chas-iot** [comment]
This is already supported for events - configure a Date type of  `event - annual`.

For annual holidays, I'm assuming that you use a calendar provider that automatically provides the dates for the next year or two.

**Comment by chas-iot** [comment]
Annualising public holidays is much more complex than annualising events such as birthdays.
* Different countries have different working weeks.
* Different countries have different rules for managing how to shift the observed holiday when the actual holiday date falls on a non-working day. For example, here in Singapore, if a holiday falls on a Saturday then, because that is considered a working day, there is no observed holiday. However, if a holiday falls on a Sunday, then the observed holiday is shifted to Monday.
* Many public holidays are actually religious holidays that are determined from calendars that can substantially vary from the 'standard' Gregorian calendar (which originated as a Christian/Roman Catholic religious calendar).
* The dates of some religious holidays can be influenced by the weather.

For these reasons, I'm not in favour of making the requested change.
